version:  '3.9'
services:
  track-service:
    image:  track_image
    container_name: track-service
    build:  UserTrackservices/
    restart:  always
    network_mode: user-network
    ports:
      - 8083:8083
    depends_on:
      - mongoService

  mongoService:
    image:  mongo
    container_name: mongoService
    ports:
      - 27017:27017
    network_mode: user-network

  authenticationService:
    image:  authentication_image
    container_name: authenticationService
    build:  UserAuthentication/
    restart:  always
    network_mode: user-network
    ports:
      - 8092:8092
    depends_on:
      - mysqlService

  mysqlService:
    image:  mysql:latest
    container_name: mysqlService
    network_mode: user-network
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  apigateway:
    container_name: apigateway
    build: demoapigateway/
    network_mode: user-network
    ports:
      - 9003:9003

  eureka-service:
    container_name: eureka-service
    build: demoEureka/
    restart: always
    network_mode: user-network
    ports:
      - 8761:8761